const createCategoriesForBrand = (categoryBrandId:string) => {
    const object = [
        {
            "categoryKey": "Earrings",
            "categoryLabel": "Earrings",
            "categorySortOrder": 1,
            "categorySortBy": "",
            "categoryStatus": true,
            "categoryMetaJson": {},
            "categoryIcon": "",
            "categoryType": "ear",
            "categoryParent": null,
            "categoryIsSet": false,
            categoryBrandId,
            modifiedBy: process.env.USER_MODIFIED_BY,
        },
        {
            "categoryKey": "Rings",
            "categoryLabel": "Rings",
            "categorySortOrder": 2,
            "categorySortBy": "",
            "categoryStatus": true,
            "categoryMetaJson": {},
            "categoryIcon": "",
            "categoryType": "finger",
            "categoryParent": null,
            "categoryIsSet": false,
            categoryBrandId,
            modifiedBy: process.env.USER_MODIFIED_BY,
        },
        {
            "categoryKey": "Necklaces",
            "categoryLabel": "Necklaces",
            "categorySortOrder": 3,
            "categorySortBy": "",
            "categoryStatus": true,
            "categoryMetaJson": {},
            "categoryIcon": "",
            "categoryType": "neck",
            "categoryParent": null,
            "categoryIsSet": false,
            categoryBrandId,
            modifiedBy: process.env.USER_MODIFIED_BY,
        },
        {
            "categoryKey": "Pendants",
            "categoryLabel": "Pendants",
            "categorySortOrder": 4,
            "categorySortBy": "",
            "categoryStatus": true,
            "categoryMetaJson": {},
            "categoryIcon": "",
            "categoryType": "neck",
            "categoryParent": null,
            "categoryIsSet": false,
            categoryBrandId,
            modifiedBy: process.env.USER_MODIFIED_BY,
        },
        {
            "categoryKey": "Chains",
            "categoryLabel": "Chains",
            "categorySortOrder": 5,
            "categorySortBy": "",
            "categoryStatus": true,
            "categoryMetaJson":{},
            "categoryIcon": "",
            "categoryType": "neck",
            "categoryParent": null,
            "categoryIsSet": false,
            categoryBrandId,
            modifiedBy: process.env.USER_MODIFIED_BY,
        },
        {
            "categoryKey": "Bracelets",
            "categoryLabel": "Bracelets",
            "categorySortOrder": 6,
            "categorySortBy": "",
            "categoryStatus": true,
            "categoryMetaJson": {},
            "categoryIcon": "",
            "categoryType": "wrist",
            "categoryParent": null,
            "categoryIsSet": false,
            categoryBrandId,
            modifiedBy: process.env.USER_MODIFIED_BY,
        },
        {
            "categoryKey": "Mangalsutras",
            "categoryLabel": "Mangalsutras",
            "categorySortOrder": 7,
            "categorySortBy": "",
            "categoryStatus": true,
            "categoryMetaJson": {},
            "categoryIcon": "",
            "categoryType": "neck",
            "categoryParent": null,
            "categoryIsSet": false,
            categoryBrandId,
            modifiedBy: process.env.USER_MODIFIED_BY,
        },
        {
            "categoryKey": "Sets",
            "categoryLabel": "Sets",
            "categorySortOrder": 8,
            "categorySortBy": "",
            "categoryStatus": true,
            "categoryMetaJson": {},
            "categoryIcon": "",
            "categoryType": "set",
            "categoryParent": null,
            "categoryIsSet": true,
            categoryBrandId,
            modifiedBy: process.env.USER_MODIFIED_BY,
        },
        {
            "categoryKey": "Pendant Sets",
            "categoryLabel": "Pendant Sets",
            "categorySortOrder": 9,
            "categorySortBy": "",
            "categoryStatus": true,
            "categoryMetaJson": {},
            "categoryIcon": "",
            "categoryType": "set",
            "categoryParent": null,
            "categoryIsSet": true,
            categoryBrandId,
            modifiedBy: process.env.USER_MODIFIED_BY,
        }
    ]
    return object
}
export {
    createCategoriesForBrand
}